config/routes.rb
Questions::Application.routes.draw do
  ActiveAdmin.routes(self)

  mount DjMon::Engine => 'dj_mon'

  resources :invitations

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/facebook"

  get "static_pages/widgetsamples"

  get "static_pages/whyreviews"

  get "static_pages/resourcesforwebdesigners"

  get "static_pages/pricing"

  get "static_pages/local_search_report"

  match '/get_fb_token' => 'users#get_fb_token'
  match '/connect_to_facebook' => 'users#connect_to_facebook'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :profiles do

    resources :reviews
    member do
      get :image_previews
    end

    resources "widgets", only: [] do
      collection do
        get "detail"
        get "summary"
      end
    end

    member do
      post :save_product_question
      post :save_page_header
      post :save_page_color
      delete :delete_image
      post :add_review_site
    end
    collection do
      post :follow_up_email
      post :resend_email
      post :yelp_score
      post :yelp_score_value
    end
  end

  resources :static_pages do
    collection do
      post :verify_payment
      get :get_payment
      post :contact_us_query
    end

    member do
      get :iframe_box
    end
  end

  resources :reviews do
    collection do
      post :on_off_product_question
    end
  end
 
  root to: 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @profile = current_user.profile if user_signed_in?
	  render home_view
  end

  def about
  end

  def facebook
  end

  def widgetsamples
  end

  def whyreviews
  end

  def resourcesforwebdesigners
  end

  def local_search_report
  end  

  def pricing
  end

  def get_payment
    @account = current_user
  end

  def verify_payment
    begin
      @account = current_user
      Stripe.api_key = Settings[:stripe_api_key]
      plan = params[:account_type]=="premium" ? Settings[:stripe_plan_49] : Settings[:stripe_plan_99]
      card_token = Stripe::Token.create( :card => { :name => params[:name_on_card], :number => params[:card_number], :exp_month => params[:exp_month], :exp_year => params[:exp_year], :cvc => params[:card_id] })
      customer_params = {:card => card_token[:id], :plan => plan, :email => @account.email}
      customer_params[:coupon] = params[:stripe_coupon] unless params[:stripe_coupon].blank?
      stripe_customer = Stripe::Customer.create(customer_params)
      if @account.update_attributes(:customer_id => stripe_customer[:id], :user_account_type => params[:account_type])
        flash[:notice] = "Payment is successful."
        redirect_to root_url
      else
        redirect_to root_url 
      end
    rescue Exception => e
      flash[:alert] = "#{e.message}"
      redirect_to root_url
    end
  end

   def iframe_box
    @profile = Profile.find(params[:id])
    @data = @profile.reviews.reverse
    @profile_page_header = ""
    @transparent = "transparent"
  end
  
  def contact_us_query
    content = params[:feedback]
    UserMailer.contact_us(content).deliver
    render :json => {:status => "ok"}.to_json
  end

private
	def home_view
		user_signed_in? ? "home_signed_in" : "home"
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.haml
%h1
  StaticPages#about
%p
  Find me in app/views/static_pages/about.html.erb

app/views/static_pages/facebook.html.erb
<div id="fb-root"></div>
<script type="text/javascript">
  // You probably don't want to use globals, but this is just example code
  var fbAppId = '183405068477171';
  var objectToLike = 'http://techcrunch.com/2013/02/06/facebook-launches-developers-live-video-channel-to-keep-its-developer-ecosystem-up-to-date/';

  // This check is just here to make sure you set your app ID. You don't
  // need to use it in production. 
  if (fbAppId === 'replace me') {
    alert('Please set the fbAppId in the sample.');
  }

  // This is boilerplate code that is used to initialize the Facebook
  // JS SDK.  You would normally set your App ID in this code.

  // Additional JS functions here
  window.fbAsyncInit = function() {
    FB.init({
      appId      : fbAppId,        // App ID
      status     : true,           // check login status
      cookie     : true,           // enable cookies to allow the server to access the session
      xfbml      : true            // parse page for xfbml or html5 social plugins like login button below
    });

    // Put additional init code here
  };

  // Load the SDK Asynchronously
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

  /*
   * This function makes a call to the og.likes API.  The object argument is
   * the object you like.  Other types of APIs may take other arguments.
   * (i.e. the book.reads API takes a book= argument.)
   *
   * Because it's a sample, it also sets the privacy parameter so that it will
   * create a story that only you can see.  Remove the privacy parameter and
   * the story will be visible to whatever the default privacy was when you
   * added the app.
   *
   * Also note that you can view any story with the id, as demonstrated with
   * the code below.
   *
   * APIs used in postLike():
   * Call the Graph API from JS:
   *   https://developers.facebook.com/docs/reference/javascript/FB.api
   * The Open Graph og.likes API:
   *   https://developers.facebook.com/docs/reference/opengraph/action-type/og.likes
   * Privacy argument:
   *   https://developers.facebook.com/docs/reference/api/privacy-parameter
   */

  function postLike() {
    FB.api(
       'https://graph.facebook.com/me/og.likes',
       'post',
       { object: objectToLike,
         privacy: {'value': 'SELF'} },
       function(response) {
         if (!response) {
           alert('Error occurred.');
         } else if (response.error) {
           document.getElementById('result').innerHTML = 'Error: ' + response.error.message;
         } else {
           document.getElementById('result').innerHTML =
             '<a href=\"https://www.facebook.com/me/activity/' + response.id + '\">' +
             'Story created.  ID is ' + response.id + '</a>';
         }
       }
    );
  }
</script>

<!--
  Login Button - https://developers.facebook.com/docs/reference/plugins/login

  This example needs the 'publish_actions' permission in order to publish an
  action.  The scope parameter below is what prompts the user for that permission.
-->

<div
  class="fb-login-button"
  data-show-faces="true"
  data-width="200"
  data-max-rows="1"
  data-scope="publish_actions">
</div>

<div>
This example creates a story on Facebook using the <a href="https://developers.facebook.com/docs/reference/ogaction/og.likes"><code>og.likes</code></a> API.  That story will just say that you like an <a href="http://techcrunch.com/2013/02/06/facebook-launches-developers-live-video-channel-to-keep-its-developer-ecosystem-up-to-date/">article on TechCrunch</a>.  The story should only be visible to you.
</div>

<div>
<input type="button" value="Create a story with an og.likes action" onclick="postLike();">
</div>

<div id="result"></div>

app/views/static_pages/get_payment.html.haml
%h3 Billing Information

=form_for @account, :url => {:action => 'verify_payment',:account_type => params[:account_type]}, :method => 'post' do |f|
  %div.field
    =label_tag "Name on card"
    =text_field_tag :name_on_card, nil, :required => true
  %div.field
    =label_tag "Card Number"
    =text_field_tag :card_number, nil, :required => true
  %div.field
    =label_tag "Expire Date:"
    =select_month nil, {:add_month_numbers_true => true}, {name: "exp_month", :required => true}
    =select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: "exp_year", :required => true}
  %div.field
    =label_tag "Security Code on Card (CVV)"
    =text_field_tag :card_id, nil, :required => true
  %div.field
    =label_tag "Discount Coupon Code"
    =text_field_tag :stripe_coupon
  %div.field
    =label_tag "Amount"
    =text_field_tag :amount, params[:account_type]=="premium" ? "$49.95" : "$99.95", {:readonly=>"readonly"}
  .actions
  =f.submit "Next"

app/views/static_pages/home.html.haml
.hero
  .container
    .row-fluid
      .span6
        .text-right
          %h1 Customer reviews for your website.
          %p
            %strong 3Questions
            makes it easy to collect and share customer reviews on your website.
            Add reviews to your website and let your customers do the selling for you.
          = link_to "Try it for free.", new_user_registration_path, class: "btn btn-large btn-primary"

      .span6
        <iframe id='myIframe' class='widget' frameBorder='0' src='http://www.get3questions.com/static_pages/7-sterling-cooper-draper-pryce/iframe_box'></iframe>
.light-grey.clearfix
  %form.text-center
    %span Free email course: "Get more customers from Google."
    .createsend-button{:data => {listid: 't/D7/F7A/9B0/3FA4BD49D4B2BF09'}, :style => 'height:27px;display:inline-block;' }
    %script 
      (function () { var e = document.createElement('script'); e.type = 'text/javascript'; e.async = true; e.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://btn.createsend1.com/js/sb.min.js?v=2'; e.className = 'createsend-script'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(e, s); })();
.container.homepage-container
  .row-fluid
    .span6.offset3
      %h2.page-header.text-center Why reviews?
  .row-fluid.unit-wrapper
    .span4.offset2.text-right
      %h4 Consumers want reviews.
      %p
      Consumers want to read reviews of your business before purchasing. Our own survey showed that the only content on your website more important than reviews is price. Why not give consumers what they want, so they don't need to leave your website?
      #{link_to 'See the research.', static_pages_whyreviews_path}
    .span3
      .well.text-center
        %strong 92%
        of users read internet reviews
        %small Source: Etailing Group
  .row-fluid.unit-wrapper
    .span4.offset2.text-center
      .well
        %strong 87%
        "POSITIVE information I've read online 
        has reinforced my decision to purchase a 
        product or service recommended to me"
        %small Source: Cone Communications
    .span3
      %h4 Reviews convert.
      %p
      Positive reviews of your business help convert prospects and visitors into paying customers. 
  .row-fluid.unit-wrapper
    .span3.offset3.text-right
      %h4 Google loves reviews.
      %p
      Local businesses with positive reviews are more likely to be found on Google.       
    .span6
      =image_tag "Google Reviews.png", { class: ["img-rounded"] }
  .row-fluid
    .span6.offset3
      %h2.page-header.text-center How we help.
  .row-fluid.unit-wrapper
    .span4.offset2.text-right
      %h4 Get more reviews.
      %p
      Increase your reviews by 10x or more, and make it easy for your biggest fans to review your business on the websites that matter - like Google, Yelp, Yellowpages.com, and TripAdvisor.
      #{link_to 'Write a sample review.', "http://www.get3questions.com/profiles/7-sterling-cooper-draper-pryce/reviews/new"}
    .span6
      =image_tag "More Reviews.png", { class: ["img-rounded"] }
  .row-fluid.unit-wrapper
    .span6.text-right
      =image_tag "Mobile Layout.png", { class: ["img-rounded"] }
    .span4
      %h4 Get bad reviews before they go social.
      %p
      A bad review that goes social can do significant damage to your reputation. 3Questions helps you capture negative feedback first so you can resolve the situation before it goes social.
  .row-fluid.unit-wrapper.shared-facebook
    .span4.offset2.text-right 
      %h4 Get shared on Facebook.
      %p
      Customers can spread the word to all their friends with one click. Reach thousands of potential customers for free. A positive review shared on Facebook is
      %strong
        the best advertising you'll ever get.
    .span6
      =image_tag "Facebook Share.png", { class: ["img-rounded"] }     
  .row-fluid.unit-wrapper.add-reviews
    .span6.text-right
      =image_tag "WidgetScreenshot.png", { class: ["img-rounded"] }
    .span3
      %h4 Add reviews to your website.
      %p
      Show off your positive reviews on your website with one of our free widgets, and convert more visitors to paying customers.
  .row-fluid.unit-wrapper
    .span4.offset2.text-right
      %h4 Look great in Google.
      %p
      Show your review rating in your Google search result and increase the likelihood a customer will click on your listing.
      #{link_to 'View a sample business profile page.', "http://www.get3questions.com/profiles/7-sterling-cooper-draper-pryce"}
    .span6
      =image_tag "Google Reviews.png", { class: ["img-rounded"] }
  %p.text-center
    = link_to "Try it for free.", new_user_registration_path, class: "btn btn-large btn-primary"
  %p.text-center.muted
    %small
      #{link_to "Plans & Pricing", static_pages_pricing_path}
  %hr
  .footer.pagination-centered
    %p © 3Questions 2013. All rights reserved.
= stylesheet_link_tag "home"

app/views/static_pages/home_signed_in.html.haml
= stylesheet_link_tag "pick-a-color"

.row
  .span8.offset2
    %h1.text-center.text-dimmed Welcome back #{current_user.first_name}!
    .well
      %h3.text-center What would you like to do?
      .row-fluid
        .span4
          = link_to "Send an invite", new_invitation_path, class: "btn btn-alt btn-large"
        .span4.text-center
          = link_to "Get invitation link", "#invite", class: "btn btn-alt btn-large", data: { toggle: "modal" }
        .span4.text-right
          = link_to "Get the widget", "#other_widget", class: "btn btn-alt btn-large", data: { toggle: "modal" }
      - if current_user.user_account_type == "custom"
        %hr/ 
        %p.text-center 
          = link_to "Add reviews to my website", "#copy-detail-embed-url", class: "btn btn-primary btn-large", data: { toggle: "modal" }
      %hr/ 
      %h3.text-center Manage your profile
      .pagination.pagination-centered
        %ul
          %li #{link_to 'Invitations', invitations_path}
          %li #{link_to 'View Profile', profile_path(current_user.profile)}
          %li #{link_to 'Edit Profile', edit_profile_path(current_user.profile)}
          %li #{link_to "Edit Account", edit_user_registration_path}
          %li #{link_to 'Edit Reviews', profile_reviews_path(current_user.profile)}
      - if current_user.user_account_type == "custom"
        %hr/ 
        %h5.text-center  Change the background color on your profile and review pages:
        %p.text-center
          =text_field_tag :page_color, @profile.page_color, :placeholder => "Select a color", :class => "pick-a-color input-small"
          =link_to 'Save', '#', {:id => "save_page_color", :class => "#{@profile.id} btn btn-primary"}
          %hr/ 
          %h5.text-center Change a header image
          %p.text-center         
            =form_for @profile, :url => {:controller => 'profiles',:action => 'save_page_header',:id => @profile.id, :class => "text-center"}, :method => 'post' do |f|
              .fileupload.fileupload-new{:data => {provides: "fileupload"}}
                .fileupload-new.thumbnail{:style => "max-width: 200px; max-height: 150px"}
                  -unless @profile.page_header_file_name.nil?
                    %span.current_image
                      = @profile.page_header_file_name
                  -else
                    You don't have any image uploaded yet
                .fileupload-preview.fileupload-exists.thumbnail{:style => "max-width: 200px; max-height: 150px; line-height: 20px;"}
                %div
                  %span.btn.btn-file
                    %span.fileupload-new Select image
                    %span.fileupload-exists Change
                    = f.file_field :page_header
                  = button_tag "Delete",{:id => "delete_page_header", :class => @profile.id, :name => "page_header"} unless @profile.page_header_file_name.nil?
                  %input{:type => "submit", :value => "Save", :class => "btn btn-primary"}/ 
      %hr/ 
      %h4.text-center Send a second request for feedback?
      %p.text-center
        = check_box_tag "resend_review_email", nil, current_user.second_email_request == true
        Yes, send a follow-up email to customers who have not provided feedback.
      %hr/ 
      %h4.text-center Display your Yelp rating on your profile page?
      %p.text-center
        = check_box_tag "display_yelp_score", nil, current_user.profile.yelp_score == true
        Yes, add my Yelp rating to my profile page.
        - if current_user.profile.yelp_score_value.nil?
          =link_to 'Add Yelp score', '#add_yelp_score',class: "btn btn-link yelp_score_rating hide", data: { toggle: "modal" }
        - else
          =link_to 'Edit Yelp score', '#add_yelp_score',class: "btn btn-link yelp_score_rating hide", data: { toggle: "modal" }
      %hr/
      %h4.text-center Send an email asking for a review?
      %p.text-center
        = check_box_tag "review_name_link", nil, current_user.follow_up_email == true
        Yes, send a follow up email asking for a review on my preferred review site (e.g., Yelp):
        - if current_user.follow_up_email == true and current_user.profile.review_link.blank? and current_user.profile.review_name.blank?
          =link_to 'Add a Review site', '#add_review_site',class: "btn btn-link review_site_link hide", data: { toggle: "modal" }
        - else
          =link_to 'Edit', '#add_review_site',class: "btn btn-link review_site_link hide", data: { toggle: "modal" }
      - if current_user.user_account_type == "custom"
        %hr/ 
        %h4.text-center Should we add a product description question to your review form?
        %p.text-center
          = check_box_tag "product_question", nil, current_user.product_description == 'on'
          Yes, add a product description question 
          =link_to 'Edit the question', '#edit_product_ques',class: "btn btn-link", data: { toggle: "modal" }
      - else
        %hr/ 
        %h4.text-center Need more options?
        %p.text-center
          = link_to "Upgrade to the Custom plan", "#{get_payment_static_pages_url(:account_type => "custom")}", class: "btn btn-primary"

#invite.modal.hide.fade
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h4
      Copy the Link
  .modal-body
    = text_area_tag :embed_url, new_profile_review_url(current_user.profile), style: "width: 80%;"
  .modal-footer
    %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"}
      Close

#copy-detail-embed-url.modal.hide.fade
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h4
      Copy this Embed URL
  .modal-body
    = text_area_tag :embed_url, "<iframe src='#{detail_profile_widgets_url(current_user.profile)}' frameborder='0' allowtransparency='true' width='90%' height='400'></iframe>", style: "width: 80%;height:65px;"
  .modal-footer
    %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"}
      Close

#copy-summary-embed-url.modal.hide.fade
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h4
      Copy this Embed URL
  .modal-body
    = text_area_tag :embed_url, "<iframe src='#{summary_profile_widgets_url(current_user.profile)}' frameborder='0' allowtransparency='true' width='200' height='400'></iframe>", style: "width: 80%;height:65px;"
  .modal-footer
    %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"}
      Close

- if current_user.user_account_type == "custom"
  #edit_product_ques.modal.hide.fade
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h4
        Edit
    .modal-body
      = label_tag "Label"
      = text_field_tag :ques, "#{@profile.product_question}"
      = label_tag "Placeholder"
      = text_field_tag :placeholder, "#{@profile.product_placeholder}"
      = hidden_field_tag :profile_id, "#{@profile.id}" 
    .modal-footer
      %button#save_product_description.btn{"aria-hidden" => "true", "data-dismiss" => "modal"}
        Save

#other_widget.modal.hide.fade
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h4
      Copy this URL
  .modal-body
    = text_area_tag :embed_url, "<iframe id='myIframe' frameBorder='0' src='#{iframe_box_static_page_url(current_user.profile)}' style='left:12px;bottom:0px;width: 22%; height: 44%; overflow:hidden;position:fixed;z-index:1;border-radius:6px 6px 6px 6px'></iframe>", style: "width: 80%;height:65px;"
  .modal-footer
    %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"}
      Close
#add_review_site.modal.hide.fade
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h4
      Add Review Site
  .modal-body
    = label_tag "Review name"
    = text_field_tag :review_name, "#{@profile.review_name}"
    = label_tag "Review link"
    = text_field_tag :review_link, "#{@profile.review_link}", :placeholder => "e.g., www.yelp.com", :rel => "tooltip", :title => "www.yelp.com"
    %label{:style => "cursor:default"}
      To get the best results, provide the link that goes directly to the review form for your profile. For example, on Yelp you would link directly to the 'Write a Review' page for your business - 
      %a{:href=>'https://www.yelp.com/writeareview/biz/cMyf8e6frO9PIutPvXpjow?return_url=%2Fbiz%2FcMyf8e6frO9PIutPvXpjow ', :target => "_blank"} like this page.
  .modal-footer
    = hidden_field_tag :profile_id, "#{@profile.id}"
    %button#save_review_name_link.btn{"aria-hidden" => "true", "data-dismiss" => "modal"}
      Save
#add_yelp_score.modal.hide.fade
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h4
      Add Yelp score
  .modal-body
    = label_tag "Yelp score"
    = select(:yelp_score_value, :status, options_for_select(["1","1.5","2","2.5","3","3.5","4","4.5","5"],"#{@profile.yelp_score_value}"))
  .modal-footer
    %button#save_yelp_score.btn{"aria-hidden" => "true", "data-dismiss" => "modal"}
      Save


=javascript_include_tag "jquery"
=javascript_include_tag "tinycolor"
=javascript_include_tag "pick-a-color"
=javascript_include_tag "bootstrap-fileupload"
=javascript_include_tag "user-account"

app/views/static_pages/iframe_box.html.haml
:css
  .widget {
    font-family: 'Lato', sans-serif;
    left:5px;
    bottom:10px;
    height: 275px; 
    overflow:hidden;
    position:fixed;
    z-index:1;
    border-radius:6px 6px 6px 6px;
  }

  .toggle {
    background: #00A285;
    color: #FFF;
    padding: 5px 10px;
    cursor: pointer;
    border-radius: 5px;
    opacity: .9;
    transition: opacity .4s;
  }

  .toggle:hover {
    opacity: 1;
  }

  .star {
    font-size: 20px;
    color: #FBD000;
    line-height: 25px;
    vertical-align: top;
    position: relative;
  }

  .text {
    line-height: 22px;
    font-size: 20px;
    font-weight: 100;
    margin-left: 2px;
  }

  .heading {
    margin-left:10px;
    color:white;
    font-size:16px;
    position:fixed;
    margin-top:6px;
  }

  .floating_box {
    left:0;
    right:0;
    top:0;
    bottom:0;
    box-shadow:0 0 5px 0 rgba(0, 0, 0, 0.2);
    margin-left:10px;
    height:283px;
    width:280px;
  }

  .modal-header > div {
    background-color:#00A285;
    height:5px;
    margin-left:-15px;
    margin-top:-9px;
    width:280px;
    border-radius:5px 5px 0px 0px;
  }

  .minimize {
    float:right;
    cursor:pointer;
  }

  .icon_left_right {
    height:28px;
    width:18px;
    margin-top:70px;
    position:absolute;
    cursor:pointer;
    padding-left:5px;
    margin-left:-7px;
  }

  .widget_right_auto {
    padding-left:6px;
    margin-left:264px;
    position:absolute;
    margin-top:-117px;
    cursor:pointer
  }

  .image_carousel {
    margin-left: 20px;
    margin-right: 20px;
    height: 182px;
    margin-top: 5px;
  }

  .modal-body {
    height:180px !important;
    width:252px;
    padding:0;
    left:0;
    overflow-y:hidden;
    text-align: center;
  }

  .modal-body p {
    text-align: center;
  }

  .border {
    border-bottom:1px solid #EEEEEE;
    width:226px
  }

  .brand {
    width: 131px;
    height: 32px;
    display: block;
  }

  .modal-footer {
    padding: 9px 10px 0;
  }

  .review-content {
    font-weight: 300;
    font-size: 1.3em;
    line-height: 1.5;
    word-wrap:break-word;
    height:60px;
    width:226px;
  }

  .signature {
    margin-top: 25px;
    font-style: italic;
  }

  .signature img {
    border-radius: 50%;
    width: 20px;
    height: 20px;
  }

  #widget-chart {
    display: block;
    margin: 0 auto;
  }

  .text-percentage {
    position: absolute;
    top: 65px;
    text-align: center;
    font-size: 36px;
    width: 225px;
  }

  .chart-wrapper {
    position: relative;
  }

  .chart-wrapper h4 {
    text-align: center;
    position: relative;
    top: -10px;
    color: rgba(0,0,0,.8);
    font-weight: 400;
    font-size: 16px;
  }

  .average {
    height: 181px;
    text-align: center;
    font-weight: 400;
    color: #666;
  }

  .average-count {
    font-size: 100px;
    line-height: 1;
    color: #00A285;
    padding-bottom: 20px;
    margin-bottom: 5px;
    border-bottom: 1px solid #eee;
  }

  .average-count small {
    font-size: 20px;
    display: block;
    color: #666;
    font-weight: 300;
    margin-top: 10px;
  }

  [class^="star-rating-"] {
    margin: 7px auto 0;
  }

%div.widget
  %div.hide.toggle{:id => "3q_logo"}
    %span.star.white &#9733;
    %span.text Reviews

  .modal.floating_box
    .modal-header
      %div
      %h4
        Read our Reviews
        %span.minimize -
    %div{:id => "foo2_prev", :class => "widget_left_auto icon_left_right"}
    .image_carousel
      .modal-body{:id => "foo2"}
        / example chart
        %div.border.chart-wrapper
          %canvas{:id => "widget-chart", "data-percentage" =>  @profile.recommended_percentage} 55%
          .text-percentage #{@profile.recommended_percentage}%
          %h4 of people recommend us
        / end example chart

        / example average rating
        %div.border.average
          .star-rating-2-5
          .average-count
            %small average rating
            4.5
          %small based on 4156 reviews
        / end example average rating

        -@data.each do |obj|
          %div.border
            %p 
              = image_tag "#{obj.score.to_f}-stars.png", class: "review-star"
            %p.muted
              %small
                =obj.created_at.strftime("Reviewed on %m/%d/%y")
            %p.review-content
              #{truncate(obj.review, :length => 54, :omission => '...')}
              -if obj.review.length > 54
                =link_to "more","#{profile_url(params[:id])}",{:target => "_blank"}
            %p.muted.signature
              = image_tag "https://graph.facebook.com/#{obj.user_id}/picture?type=small" unless obj.user_id.nil?
              %small
                =obj.reviewer_first
                #{obj.reviewer_last.first}#{',' unless obj.city.blank?}
                =obj.city
    %div{:id => "foo2_next", :class => "widget_right_auto icon_left_right"}
    .modal-footer
      %p.muted.text-center
        %small
          Powered by
          %a.brand-dark{href: "http://www.get3questions.com", :target => "_blank"}
            3Questions


=javascript_include_tag "iframe-widget-chart"

app/views/static_pages/resourcesforwebdesigners.html.haml
%h3.text-center Resources for Web Designers
#container.js-masonry{'data-masonry-options' => '{ "columnWidth": 0, "itemSelector": ".item" }'}
  .well.well-small.span3.item{:style=>"width:235px"}
    %p.text-center
      This is a sample resource.
    %h1.text-center
      XX
    %p.text-center
      Here is some text about it.
    %p.muted.text-center
      %small
        Source: #{link_to 'Nowhere', "#"}