config/routes.rb
Questions::Application.routes.draw do
  ActiveAdmin.routes(self)

  mount DjMon::Engine => 'dj_mon'

  resources :invitations

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/facebook"

  get "static_pages/widgetsamples"

  get "static_pages/whyreviews"

  get "static_pages/resourcesforwebdesigners"

  get "static_pages/pricing"

  get "static_pages/local_search_report"

  match '/get_fb_token' => 'users#get_fb_token'
  match '/connect_to_facebook' => 'users#connect_to_facebook'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :profiles do

    resources :reviews
    member do
      get :image_previews
    end

    resources "widgets", only: [] do
      collection do
        get "detail"
        get "summary"
      end
    end

    member do
      post :save_product_question
      post :save_page_header
      post :save_page_color
      delete :delete_image
      post :add_review_site
    end
    collection do
      post :follow_up_email
      post :resend_email
      post :yelp_score
      post :yelp_score_value
    end
  end

  resources :static_pages do
    collection do
      post :verify_payment
      get :get_payment
      post :contact_us_query
    end

    member do
      get :iframe_box
    end
  end

  resources :reviews do
    collection do
      post :on_off_product_question
    end
  end
 
  root to: 'static_pages#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :address, :business_name, :city, :phone, :state, :zip, :image, :description, 
    :image_file_name, :image_content_type, :image_updated_at, :image_file_size,:user_id, :website, :review_link, :review_name, :product_question, :product_placeholder, :page_header, :page_color

  validates :address, :business_name, :city, :phone, :state, :zip, :description, presence: true

  belongs_to :user

  has_many :reviews
  has_many :invitations

  has_attached_file :image,
    styles: {
    #thumb: '100x100>',
    #square: '200x200#',
    standard: [ "300x300>", :png ],
    rating_4_stars: { processors: [ :thumbnail, :watermark ], watermark_type: :four_stars, geometry: "300x300>" },
    rating_5_stars: { processors: [ :thumbnail, :watermark ], watermark_type: :five_stars, geometry: "300x300>" }
  },
  default_style: :standard
  
  has_attached_file :page_header,
    styles: {
    standard: [ "300x300>", :png ],
  },
  default_style: :standard

  def recommended_percentage
    return 0.0 if reviews.blank?
    100 * reviews.where(recommendation: true).count / reviews.count
  end

  def average_score
    return 0.0 if reviews.blank?
    (self.reviews.average(:score) * 2).round / 2.0
  end

  def to_param
    if self.id.present? && self.business_name.present?
      [ self.id, self.business_name.parameterize].join("-")
    else
      super
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_filter :authenticate_user!, except: [:show]

  expose(:profiles) { Profile.all }
  expose(:profile) { current_user.profile }

  def index
  end

  def show
    self.profile = Profile.find(params[:id])
    @profile_name = Profile.find(params[:id]).business_name
    @profile_page_color = Profile.find(params[:id]).page_color
    @profile_page_header = Profile.find(params[:id]).page_header_file_name
    if params.has_key?('post_id')
      self.profile.reviews.find(params[:review_id]).update_attributes(:user_id => session[:facebook_user_id], :reviewer_first => session[:facebook_user_fname], :reviewer_last => session[:facebook_user_lname])
    end
  end

  def new
    render "edit"
  end

  def edit
  end

  def update
    begin
      if profile.update_attributes(params[:profile])
        redirect_to profile, notice: t("profiles.update.success", url: new_invitation_url)
      else
        render action: "edit"
      end
    rescue
      flash[:alert] = "Something went wrong"
      redirect_to root_url
    end
  end

  def destroy
    profile.destroy
    redirect_to profiles_url
  end

  def image_previews
    render layout: false
  end

  def save_product_question
    @profile = Profile.find(params[:id])
    @profile.update_attributes(:product_question => params[:label], :product_placeholder => params[:placeholder])
    render :text => "ok"
 end

  def save_page_header
    @profile = Profile.find(params[:id])
    @profile.update_attributes(params[:profile])
    redirect_to :back
  end

  def save_page_color
    @profile = Profile.find(params[:id])
    @profile.update_attribute('page_color', params[:color])
    render :text => "ok"
  end

  def delete_image
    @profile = Profile.find(params[:id])
    if params[:delete_column] == "page_header"
      @profile.page_header.destroy
    else
      @profile.image.destroy
    end
    @profile.save
    render :text => "ok"
  end

  def add_review_site
    @profile = Profile.find(params[:id])
    @profile.update_attributes(:review_name => params[:review_name], :review_link => params[:review_link])
    render :text => "ok"
  end

  def follow_up_email
   current_user.update_attribute('follow_up_email', params[:status])
   render :text => "ok"
  end
 
  def resend_email
   current_user.update_attribute('second_email_request', params[:status])
   render :text => "ok"
  end
 
  def yelp_score
   current_user.profile.update_attribute('yelp_score', params[:status])
   render :text => "ok"
  end
  
  def yelp_score_value
   current_user.profile.update_attribute('yelp_score_value', params[:value])
   render :text => "ok"
  end
 
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
.row
  .span4
    = simple_form_for(profile, html: {class: "form-horizontal" }, html: {class: "well" } ) do |f|
      %fieldset
        = f.input :business_name, as: :string
        = f.input :description, as: :string
        = f.input :address, as: :string
        = f.input :city, as: :string
        = f.input :state, as: :string
        = f.input :zip, as: :string
        = f.input :phone, as: :string, placeholder: 'xxx-xxx-xxxx',input_html: {class: "bfh-phone", "data-format" => "ddd-ddd-dddd", "data-number" => profile.phone}
        = f.input :website, as: :string, placeholder: 'www.company.com'
        = f.input :image, as: :file, label: "Add a logo or photo"
        - unless profile.image_file_name.nil?
          %span.current_image
            = label_tag "Current image is #{profile.image_file_name}"
          = button_tag "Delete",{:id => "delete_profile_image", :class => profile.id, :name => "image"}

      .form-actions
        %input.btn.btn-primary{:type => "submit", :value => "Submit"}/
  -#.span8
  -#  %h4 3Questions helps your business:
  -#  %ol
  -#    %li
  -#     Get instant customer feedback
  -#    %li
  -#      Get to your customers before they post a negative review
  -#    %li
  -#      Get more positive reviews

app/views/profiles/_profile.html.haml
%tr
  %td
    = profile.business_name
  %td
    = profile.address
  %td
    = profile.city
  %td
    = profile.state
  %td
    = profile.zip
  %td
    = profile.phone
  %td
    = link_to 'Show', profile
  %td
    = link_to 'Review', new_profile_review_path(profile)
  -if profile.id == current_user.profile.id
    %td
      = link_to 'Edit', edit_profile_path(profile)
    %td
      = link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }

app/views/profiles/_reviews.html.haml
.review-item
  .clearfix
    %div{:class => "star-rating-"+review.score.to_s.gsub('.','-')+" pull-left"}
    %p.pull-right.text-green
      &#10004;
      Recommends this business
  %p.muted
    %small
  %p.review-content{:style=>"word-wrap:break-word"}
    #{review.review}
  %p.muted
    %small
      =review.created_at.strftime("%m/%d/%y")
      by
      = image_tag "https://graph.facebook.com/#{review.user_id}/picture?type=small" unless review.user_id.nil?
      =review.reviewer_first
      #{review.reviewer_last.first}#{',' unless review.city.blank?}
      =review.city
      %br/
      =review.product_description
  -#%ul.children
    -#%li  
      -#%p 
        -#%strong Business name says:
        -#Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer elementum, orci quis aliquam tempus, dolor magna laoreet lectus, vitae feugiat urna tellus eget eros. Sed convallis erat vitae lorem viverra ornare. Aenean magna lacus, pellentesque id viverra nec, sollicitudin quis mi.

app/views/profiles/edit.html.haml
%h3 Setup Your Profile

= render 'form'

= link_to 'Show', profile
|
= link_to 'Back', profiles_path

app/views/profiles/image_previews.html.haml
%section
  %article
    %h1
      Default (medium)
    = image_tag profile.image.url

  %article
    %h1
      4 Stars
    = image_tag profile.image.url(:rating_4_stars)

  %article
    %h1
      5 Stars
    = image_tag profile.image.url(:rating_5_stars)

app/views/profiles/index.html.haml
.page-header
  %h3
    Business Directory
    %small
      These are our awesome customers.

%table.table.table-striped
  %thead
    %tr
      %th Business name
      %th Address
      %th City
      %th State
      %th Zip
      %th Phone
      %th
      %th
      %th
      %th
  %tbody
    = render profiles

= link_to 'New Profile', new_profile_path, class:"btn btn-large btn-success"

app/views/profiles/show.html.haml
.row-fluid
  .span3
    .sidebar.text-center
      %div{:itemscope => "", :itemtype => "http://schema.org/LocalBusiness"}
        %a{:href => "#", :data => {"toggle" => "collapse", "target" => "#company-info"}} View company info
        %div#company-info.collapse
          %p
            %address
              = profile.address
              %br/
              %span
                #{profile.city},
                = profile.state
                = profile.zip
              %br/
              %abbr{title: "Phone"} P:
              = profile.phone
              %br/ 
              #{link_to "#{profile.website}", "http://#{profile.website}", target: "_blank"}
            %hr/ 
            %strong About us
            %br/ 
            =profile.description
        %hr/ 
        %div.border.chart-wrapper
          %canvas{:id => "widget-chart", "data-percentage" => "#{profile.recommended_percentage}"} 55%
          .text-percentage #{profile.recommended_percentage}%
          %p of people recommend us
        %hr/
        - if profile.reviews.present?
          %meta{:itemprop => "ratingValue", :content => "#{profile.average_score.to_s}"}
            %div{:class => "star-rating-"+profile.average_score.to_s.gsub('.','-').gsub('-0',""), :style => "margin-left:50px"}
          %strong.average-score #{profile.average_score.to_s}

          %span{:itemprop => "ratingCount", class: "rating-count"}
            based on
            %strong 
              = profile.reviews.count
            reviews
        %hr/ 
        - if profile.yelp_score and !profile.yelp_score_value.nil?
          %h3 Our Yelp score 
          %a{:href => "#"} 
            .yelp-logo
            %div{:class => "yelp-rating-"+profile.yelp_score_value.gsub('.','-').gsub('-0',"")}
          %hr/ 
        #{link_to "Review this business", new_profile_review_url(profile), class: "btn btn-primary btn-large btn-block"}
      %p.sidebar-footer
        Verified reviews provided by 3Questions

  .span9
    .review-item
      %h1.text-center
        %span{:itemprop => "name"}
          #{profile.business_name} reviews
    - if profile.reviews.present?
      %ul.unstyled
        - profile.reviews.reverse.each do |review|
          %li
            -if current_user.nil? and review.public == true
              =render 'reviews',{:review => review}
            -elsif !current_user.nil?
              =render 'reviews',{:review => review}
    -else
      %p 
        This business has not been reviewed yet. Be the first to #{link_to "write a review", new_profile_review_url(profile)}.

=javascript_include_tag "jquery"
=javascript_include_tag "profile"