config/routes.rb
Questions::Application.routes.draw do
  ActiveAdmin.routes(self)

  mount DjMon::Engine => 'dj_mon'

  resources :invitations

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/facebook"

  get "static_pages/widgetsamples"

  get "static_pages/whyreviews"

  get "static_pages/resourcesforwebdesigners"

  get "static_pages/pricing"

  get "static_pages/local_search_report"

  match '/get_fb_token' => 'users#get_fb_token'
  match '/connect_to_facebook' => 'users#connect_to_facebook'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :profiles do

    resources :reviews
    member do
      get :image_previews
    end

    resources "widgets", only: [] do
      collection do
        get "detail"
        get "summary"
      end
    end

    member do
      post :save_product_question
      post :save_page_header
      post :save_page_color
      delete :delete_image
      post :add_review_site
    end
    collection do
      post :follow_up_email
      post :resend_email
      post :yelp_score
      post :yelp_score_value
    end
  end

  resources :static_pages do
    collection do
      post :verify_payment
      get :get_payment
      post :contact_us_query
    end

    member do
      get :iframe_box
    end
  end

  resources :reviews do
    collection do
      post :on_off_product_question
    end
  end
 
  root to: 'static_pages#home'

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base

  attr_accessible :email, :first_name, :last_name, :phone, :medium, :profile_id

  belongs_to :user
  has_one :review
  belongs_to :profile

  validates :first_name, :last_name, :medium, presence: true

  validates :email, format: { with: /\A[^@]+@[^@]+\z/, message: "Please enter a valid email", if: :medium_email? }
  validates :phone, format: { with: /^\d{3}-\d{3}-\d{4}$/, message: "Please enter a 10 digit phone number
                              without country code, spaces, dashes or any other character", if: :medium_phone? }

  def medium_email?
    self.medium == "email"
  end

  def medium_phone?
    self.medium == "phone"
  end

  def phone_with_country_code
    "+1#{self.phone.gsub('-','')}"
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  before_filter :authenticate_user!

  expose(:invitations) { current_user.invitations }
  expose :invitation

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if invitation.valid?
      invitation.save!
      invitation.destroy unless send_invitation(invitation)
      redirect_to new_invitation_url, notice: t("invitations.create.success")
    else
      render "new"
    end
  end

  def update
    if invitation.save
      redirect_to invitation, notice: t("invitations.update.success")
    else
      render "edit"
    end
  end

  def destroy
    invitation.destroy
    redirect_to invitations_url
  end

  private

  def send_invitation(invitation)
    UserMailer.invitation_email(invitation).deliver and return true if invitation.medium_email?
    send_invitation_sms(invitation) if invitation.medium_phone?
  end

  def send_invitation_sms(invitation)
    begin
      TwilioGateway.new.send_sms(
        from: Settings.twilio_outgoing_no,
        to: invitation.phone_with_country_code,
        body: "#{invitation.user.profile.business_name} invites you to provide feedback - #{new_profile_review_url(invitation.user.profile)}"
      )
    rescue Twilio::REST::RequestError => e
      invitation.errors[:phone] << "is not a valid Phone number"
      return false
    end
    true
  end

end

app/helpers/invitations_helper.rb
module InvitationsHelper

  def options_for_invitation_medium
    [
      [ "Invite via Email", "email" ],
      [ "Invite via Phone", "phone" ]
    ]
  end

end

app/views/invitations/_form.html.haml
= simple_form_for(invitation, html: {class: "form-horizontal" }, html: {class: "well" } ) do |f|
  %fieldset
    = f.input :first_name, as: :string
    = f.input :last_name, as: :string
    = f.input :medium, collection: options_for_invitation_medium, include_blank: false, label: false
    = f.input :email, as: :string
    = f.input :phone, as: :string, placeholder: '1234567890',input_html: {class: "bfh-phone", "data-format" => "ddd-ddd-dddd", "data-number" => invitation.phone}
    = f.hidden_field :profile_id, :value => current_user.profile.id
  .form-actions
    = f.submit "Send", class: "btn btn-primary"

app/views/invitations/_invitation.html.haml
%tr
  %td= invitation.first_name
  %td= invitation.last_name
  %td= invitation.email
  %td= invitation.phone
  %td= link_to 'Show', invitation
  %td= link_to 'Edit', edit_invitation_path(invitation)
  %td= link_to 'Destroy', invitation, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/invitations/edit.html.haml
%h1 Editing invitation

= render 'form'

= link_to 'Show', invitation
\|
= link_to 'Back', invitations_path

app/views/invitations/index.html.haml
%h1 Your Invitations

%table.table.table-striped
  %thead
    %tr
      %th First name
      %th Last name
      %th Email
      %th Phone
      %th
      %th
      %th

  %tbody
    = render invitations

%p
  #{link_to "Send an Invite", new_invitation_path, class: "btn btn-large btn-success" }
%p
  %br/
  #{link_to 'Home', static_pages_home_path} | #{link_to 'View Profile', profile_path(current_user.profile)} | #{link_to 'Edit Profile', edit_profile_path(current_user.profile)} | #{link_to "Edit Account", edit_user_registration_path}

app/views/invitations/new.html.haml
%h3 Send a Review Invite

.row
  .span4
    = render 'form'

app/views/invitations/show.html.haml
%p#notice= notice

%p
  %b First name:
  = invitation.first_name
%p
  %b Last name:
  = invitation.last_name
%p
  %b Email:
  = invitation.email
%p
  %b Phone:
  = invitation.phone

= link_to 'Edit', edit_invitation_path(invitation)
\|
= link_to 'Back', invitations_path