config/routes.rb
Questions::Application.routes.draw do
  ActiveAdmin.routes(self)

  mount DjMon::Engine => 'dj_mon'

  resources :invitations

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/facebook"

  get "static_pages/widgetsamples"

  get "static_pages/whyreviews"

  get "static_pages/resourcesforwebdesigners"

  get "static_pages/pricing"

  get "static_pages/local_search_report"

  match '/get_fb_token' => 'users#get_fb_token'
  match '/connect_to_facebook' => 'users#connect_to_facebook'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :profiles do

    resources :reviews
    member do
      get :image_previews
    end

    resources "widgets", only: [] do
      collection do
        get "detail"
        get "summary"
      end
    end

    member do
      post :save_product_question
      post :save_page_header
      post :save_page_color
      delete :delete_image
      post :add_review_site
    end
    collection do
      post :follow_up_email
      post :resend_email
      post :yelp_score
      post :yelp_score_value
    end
  end

  resources :static_pages do
    collection do
      post :verify_payment
      get :get_payment
      post :contact_us_query
    end

    member do
      get :iframe_box
    end
  end

  resources :reviews do
    collection do
      post :on_off_product_question
    end
  end
 
  root to: 'static_pages#home'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  include AssetUrlHelper

  expose :profile
  expose(:reviews) { profile.reviews }
  expose :review

  def index
  end

  def show
  end

  def new
    @profile_page_color = profile.page_color
    @profile_page_header = profile.page_header_file_name
  end

  def edit
  end

  def create
    if review.save
      review.update_attribute('invitation_id', params[:invitation_id]) if review.sharable?
      review.invitation.update_attribute('send_email', false) if review.sharable? && !params[:invitation_id].blank? && review.profile.review_link !="" && review.profile.review_name != "" && review.profile.user.follow_up_email == true
      profile_path = profile_url(params[:profile_id])
      UserMailer.review_email(review,profile_path).deliver
      flash[:notice] = t("reviews.create.success")
      if review.sharable? && params[:fb_share].present?
        session[:redirect_to] = review_share_url
        session[:onerror_redirect_to] = profile_url(profile)
        redirect_to connect_to_facebook_url
      end
      redirect_to [ profile ] unless params[:fb_share].present?
    else
      render action: "new"
    end
  end

  def update
    if review.save
      redirect_to review_share_url and return if review.sharable? && params[:fb_share].present?
      redirect_to [ profile ]
    else
      render action: "edit"
    end
  end

  def destroy
    review.destroy
    redirect_to profile_reviews_path(profile)
  end

  def on_off_product_question
   current_user.update_attribute('product_description', params[:status])
   render :text => "ok"
  end

  private

  def review_share_url
    name =         "#{review.reviewer_first} gives #{review.profile.business_name} #{review.score} out of 5 stars."
    page_link =    profile_review_url(review.profile, review)
    caption =     "#{review.profile.description} | #{review.profile.city}, #{review.profile.state}"
    description =  review.review || "N.A."
    picture_url =  review.profile.image.url

    url = "https://www.facebook.com/dialog/feed?app_id=#{Settings.fb_app_id}&"\
    "link=#{page_link}&"\
    "picture=#{picture_url}&"\
    "name=#{name}&"\
    "caption=#{caption}&"\
    "description=#{description}&"\
    "redirect_uri=#{profile_url(profile)}?review_id=#{review.id}&"\
    "display=page"

    URI.encode(url)
  end

end

app/views/reviews/_form.html.haml
= image_tag profile.page_header.url, { class: ["custom-profile-image"] } unless profile.page_header_file_name.nil?
= simple_form_for([profile, review]) do |f|
  = f.error_notification
  .row-fluid
    .span6.offset3
      .white-wrapper
        %fieldset
          %legend
            Feedback for <strong> #{profile.business_name} </strong>
          .form-inputs
            = f.input :score, collection: [5,4,3,2,1], label: 'How was your experience?'
            .control-group
              #review-stars
            = f.input :recommendation, as: :radio_buttons, label: 'Would you recommend to a friend?'
            = f.input :review, input_html: { rows: 6}, label: 'What would you tell a friend?'
            = f.input :reviewer_first, label: "First Name"
            = f.input :reviewer_last, label: "Last Name"
            = f.input :city, label: "City"
            -if profile.user.user_account_type == "custom" and profile.user.product_description == "on"
              = content_tag :p, "<span id='review_product_question'>#{profile.product_question}</span>".html_safe
              = f.input :product_description,placeholder: "#{profile.product_placeholder}", input_html: { rows: 4 }, label: false
            -#= f.input :contact, label: false do
              -#%label.checkbox.inline
                -#= f.check_box :contact
                -#We're sorry you had a bad experience. Is it ok to contact you? 
            = f.input :public, label: false do
              %label.checkbox.inline
                = f.check_box :public,{:checked => true}
                %small It's OK to post my feedback as an online review using my first name and last initial - e.g., "Joe S."
            = hidden_field_tag :invitation_id,"", :value => params[:invite_id]
          .form-actions
            %input.btn.btn-primary{ type: "submit", value: "Share on Facebook", name: "fb_share", id: "fb-share-button" }
            %button.btn.btn-primary{ type: "submit", name: "post" } Submit
        %p.instruction
          *
          %small 
            Fields marked with asterisk are required

app/views/reviews/_review.html.haml
%tr
  %td
    = review.profile_id
  %td
    = review.score
  %td
    = review.recommendation == true ? "Yes" : "No"
  %td
    = review.review
  %td
    = review.public == true ? "1" : "2"
  %td
    = link_to 'Show', [profile, review]
  -if profile.id == current_user.profile.id
    %td
      = link_to 'Edit', edit_profile_review_path(profile, review)
    %td
      = link_to 'Destroy', [profile, review], method: :delete, data: { confirm: 'Are you sure?' }

app/views/reviews/edit.html.haml
= render 'form'

= link_to 'Show', [profile, review]
|
=link_to 'Back', profile_reviews_path(profile), class: "btn"

app/views/reviews/index.html.haml
%h3 Listing reviews

%table.table
  %thead
    %tr
      %th Profile
      %th Score
      %th Recommend to a friend?
      %th Review
      %th Public?
      %th
      %th
  %tbody
    = render reviews

%br/

= link_to 'New Review', new_profile_review_path(profile), class: "btn btn-primary"

app/views/reviews/new.html.haml
= render "form"

-#= link_to 'Back', profile_reviews_path(profile), class: "btn"

app/views/reviews/show.html.haml
- content_for :meta_tags do
  %meta{ content: "183405068477171", property: "fb:app_id"}
  %meta{ content: "three_questions:business", property: "og:type"}
  %meta{ content: request.url, property: "og:url"}
  %meta{ content: "Sample Business", property: "og:title"}
  %meta{ content: "http://serene-reef-8689.herokuapp.com/assets/rails-a3386665c05a2d82f711a4aaa72d247c.png", :property => "og:image"}/

%p
  %b
    = profile.business_name
  gets
  %b
    = review.score
  stars from me!

= review.review

%dl.dl-horizontal
  %dt
    Number of reviews:
  %dd
    = profile.reviews.count

  %dt
    Business Name:
  %dd
    = profile.business_name

  %dt
    Score:
  %dd
    = review.score

  %dt
    Recommendation:
  %dd
    = review.recommendation

%p
  Review:
  = review.review
-if profile.id == current_user.profile.id
  = link_to 'Edit', edit_profile_review_path(profile, review), class: "btn"
= link_to 'Back', profile_reviews_path(profile), class: "btn"